#!/usr/bin/env python
import unittest
import os, sys, argparse

from tests.test_database import DatabaseTestCase
from tests.test_utils import UtilTestCase

def dbSuite():
	suite = unittest.TestSuite()

	suite.addTest(DatabaseTestCase('testShow'))
	suite.addTest(DatabaseTestCase('testPerson'))
	suite.addTest(DatabaseTestCase('testSequence'))
	suite.addTest(DatabaseTestCase('testShot'))
	suite.addTest(DatabaseTestCase('testElement'))
	suite.addTest(DatabaseTestCase('testFix'))
	suite.addTest(DatabaseTestCase('testPF'))
	suite.addTest(DatabaseTestCase('testTake'))

	return suite

def utilSuite():
	suite = unittest.TestSuite()

	suite.addTest(UtilTestCase('testIsSanitary'))
	suite.addTest(UtilTestCase('testFrameSequence'))

	return suite

if __name__ == '__main__':
	os.environ['HELIX_WORK'] = '/tmp/helixTest/work'
	os.environ['HELIX_RELEASE'] = '/tmp/helixTest/release'
	os.environ['HELIX_DB'] = '/tmp/helixTest/test.db'

	suites = {
		'db': dbSuite,
		'utils': utilSuite
	}

	parser = argparse.ArgumentParser('Run various/all test suites')

	parser.add_argument(
		'mode',
		choices=('suites', 'run'),
		help='Whether to run the test suite(s) or some other action.'
	)
	parser.add_argument(
		'--suites', '-s',
		choices=list(suites.keys()),
		default=list(suites.keys()),
		nargs='+',
		help='Which specific test suites to run'
	)

	args = parser.parse_args()

	if args.mode == 'suites':
		print 'Available suites: ' + ', '.join(suites.keys())
	elif args.mode == 'run':
		for sName in args.suites:
			msg = '# RUNNING SUITE: {} #'.format(sName)
			print '#' * len(msg)
			print msg
			print '#' * len(msg)

			testResult = unittest.TextTestRunner(verbosity=2).run(suites[sName]())

