#!/usr/bin/env python

import unittest
import os, shutil, sys, argparse

from helix.database.sql import Manager
from helix.database.show import Show
from helix.database.person import Person
from helix.database.sequence import Sequence
from helix.database.shot import Shot
from helix.database.element import Element
from helix.database.fix import Fix
import helix.environment.environment as env

'''
	MAJOR TODO:
	1. Install script for first time users
	2. Environment tab in config
'''

class DatabaseTestCase(unittest.TestCase):
	def testShow(self):
		# TODO: validate table columns are in object attrs
		show = Show('foobar')

		self.assertTrue(show._exists)
		self.assertTrue(show.exists())
		self.assertEqual(show.exists(fetch=True), ('foobar', None, '/tmp/helixTest/work/foobar', '/tmp/helixTest/release/foobar', 'spaouellet', show.creation))
		self.assertEqual(show.alias, 'foobar')
		self.assertEqual(show.name, None)
		self.assertEqual(show.work_path, '/tmp/helixTest/work/foobar')
		self.assertEqual(show.release_path, '/tmp/helixTest/release/foobar')
		self.assertEqual(show.author, 'spaouellet')

		self.assertEqual(show.get('alias'), 'foobar')

		# Nonextant attributes
		self.assertIs(show.get('randomAttr'), None)
		self.assertEqual(show.get('randomAttr', 'default'), 'default')

		self.assertIn(show.table, Manager.TABLE_LIST)
		self.assertTrue(os.path.exists(show.work_path))
		self.assertTrue(os.path.exists(show.release_path))

		# Test dummy show doesn't exist
		nonextant = Show('nonextant')
		self.assertFalse(nonextant._exists)
		self.assertFalse(nonextant.exists())
		self.assertIs(nonextant.exists(fetch=True), None)

		show.set('name', 'Testing')

		del show
		show = Show('foobar') # Remaking, should have saved show.name

		self.assertEqual(show.name, 'Testing')

		# Test setting on a non-db-extant show
		show2 = Show('show2')

		show2.set('name', 'Show2') # We set without inserting
		del show2
		show2 = Show('show2')
		self.assertIs(show2.name, None)
		# Now set while inserting
		show2.set('name', 'Show2', insertIfMissing=True)
		del show2
		show2 = Show('show2')
		self.assertEqual(show2.name, 'Show2')

		# Table columns exist in attrs
		with Manager(willCommit=False) as mgr:
			for c in [c[0] for c in mgr.getColumnNames(show2.table)]:
				self.assertTrue(hasattr(show2, c))

		# Try inserting again, should fail
		self.assertFalse(show.insert())

	def testPerson(self):
		person = Person('spaouellet')

		self.assertTrue(person._exists)
		self.assertTrue(person.exists())
		self.assertEqual(person.full_name, None)
		self.assertEqual(person.department, None)
		self.assertIn(person.table, Manager.TABLE_LIST)
		self.assertTrue(person.exists())

		# Random person
		self.assertFalse(Person('bob').exists())

		person.set('full_name', 'Sasha Ouellet')
		del person
		person = Person('spaouellet')
		self.assertEqual(person.full_name, 'Sasha Ouellet')

		with Manager(willCommit=False) as mgr:
			for c in [c[0] for c in mgr.getColumnNames(person.table)]:
				self.assertTrue(hasattr(person, c))

		# Try inserting again, should fail
		self.assertFalse(person.insert())

	def testSequence(self):
		seq1 = Sequence(200)

		self.assertFalse(seq1._exists)
		self.assertFalse(seq1.exists())
		self.assertTrue(Show(seq1.show).exists())

		with self.assertRaises(ValueError):
			badSeq = Sequence(100, show='nonextant')

		with self.assertRaises(ValueError):
			badSeq = Sequence(None)

		# Bad number
		with self.assertRaises(ValueError):
			badSeq = Sequence('foo')

		# Should convert
		self.assertEqual(Sequence('100', show='foobar').num, 100)

		self.assertIn(seq1.table, Manager.TABLE_LIST)
		self.assertFalse(os.path.exists(seq1.work_path))
		self.assertFalse(os.path.exists(seq1.release_path))

		with Manager(willCommit=False) as mgr:
			for c in [c[0] for c in mgr.getColumnNames(seq1.table)]:
				self.assertTrue(hasattr(seq1, c))

		# Try inserting again, should fail
		self.assertFalse(Sequence(100, show='foobar').insert())

	def testShot(self):
		shot = Shot(100, 100)

		self.assertTrue(shot._exists)
		self.assertTrue(shot.exists())
		self.assertTrue(Show(shot.show).exists())
		self.assertTrue(Sequence(shot.sequence).exists())

		self.assertIn(shot.table, Manager.TABLE_LIST)
		self.assertTrue(os.path.exists(shot.work_path))
		self.assertTrue(os.path.exists(shot.release_path))

		with self.assertRaises(ValueError):
			badShot = Shot(100, None, show='nonextant')

		with self.assertRaises(ValueError):
			badShot = Shot(None, None, 'foobar')

		# Bad shot number
		with self.assertRaises(ValueError):
			badShot = Shot('foo', 100, 'foobar')

		# Bad seq number
		with self.assertRaises(ValueError):
			badShot = Shot(100, 'foo', 'foobar')

		# Should convert
		self.assertEqual(Shot('100', '100', 'foobar').num, 100)
		self.assertEqual(Shot('100', '100', 'foobar').sequence, 100)

		# Non-extant sequence
		with self.assertRaises(ValueError):
			badShot = Shot(100, 200, 'foobar')

		with Manager(willCommit=False) as mgr:
			for c in [c[0] for c in mgr.getColumnNames(shot.table)]:
				self.assertTrue(hasattr(shot, c))

		# Try inserting again, should fail
		self.assertFalse(shot.insert())

	def testElement(self):
		el = Element('test', 'prop', 'foobar', 100, 100)

		self.assertFalse(el._exists)
		self.assertFalse(el.exists())
		self.assertTrue(Show(el.show).exists())
		self.assertTrue(Sequence(el.sequence, el.show).exists())
		self.assertTrue(Shot(el.shot, el.sequence, el.show).exists())

		self.assertTrue(Element('test', 'prop', 'foobar').exists())

		self.assertIn(el.table, Manager.TABLE_LIST)
		self.assertFalse(os.path.exists(el.work_path))
		self.assertFalse(os.path.exists(el.release_path))

		# No element type
		with self.assertRaises(ValueError):
			badEl = Element('foo', None, 'foobar')

		# Can be nameless, but only if we give shot and seq
		with self.assertRaises(ValueError):
			badEl = Element(None, 'prop', 'foobar')

		# Should be procedurally generated
		self.assertIsNotNone(Element(None, 'prop', 'foobar', 100, 100).name)

		# Improper element type
		with self.assertRaises(ValueError):
			badEl = Element('foo', 'bar', 'foobar')

		with Manager(willCommit=False) as mgr:
			for c in [c[0] for c in mgr.getColumnNames(el.table)]:
				self.assertTrue(hasattr(el, c))

		# Try inserting again, should fail
		self.assertFalse(Element('test', 'prop', 'foobar').insert())

	def testFix(self):
		fix1 = Fix('Test fix', 'This is the body', show='foobar')

		self.assertTrue(fix1._exists)
		self.assertTrue(fix1.exists())

	@classmethod
	def setUpClass(cls):
		if not os.path.exists(os.environ['HELIX_DB']):
			if not os.path.isdir(os.path.dirname(os.environ['HELIX_DB'])):
				os.makedirs(os.path.dirname(os.environ['HELIX_DB']))

			open(os.environ['HELIX_DB'], 'w').close()

		with Manager() as mgr:
			mgr.initTables()

			Person('spaouellet').insert()
			Show('foobar', makeDirs=True).insert()
			Sequence(100, 'foobar', makeDirs=True).insert()
			Shot(100, 100, 'foobar', makeDirs=True).insert()
			Element('test', 'prop', 'foobar', makeDirs=True).insert()
			Fix('Test fix', 'This is the body', show='foobar').insert()

			env.show = 'foobar'

	@classmethod
	def tearDownClass(cls):
		if os.path.isdir(os.environ['HELIX_WORK']):
			shutil.rmtree(os.environ['HELIX_WORK'])

		if os.path.isdir(os.environ['HELIX_RELEASE']):
			shutil.rmtree(os.environ['HELIX_RELEASE'])

		if os.path.exists(os.environ['HELIX_DB']):
			os.remove(os.environ['HELIX_DB'])

def dbSuite():
	suite = unittest.TestSuite()

	suite.addTest(DatabaseTestCase('testShow'))
	suite.addTest(DatabaseTestCase('testPerson'))
	suite.addTest(DatabaseTestCase('testSequence'))
	suite.addTest(DatabaseTestCase('testShot'))
	suite.addTest(DatabaseTestCase('testElement'))
	suite.addTest(DatabaseTestCase('testFix'))

	return suite

if __name__ == '__main__':
	os.environ['HELIX_WORK'] = '/tmp/helixTest/work'
	os.environ['HELIX_RELEASE'] = '/tmp/helixTest/release'
	os.environ['HELIX_DB'] = '/tmp/helixTest/test.db'

	suites = {
		'db': dbSuite,
	}

	parser = argparse.ArgumentParser('Run various/all test suites')

	parser.add_argument(
		'mode',
		choices=('suites', 'run'),
		help='Whether to run the test suite(s) or some other action.'
	)
	parser.add_argument(
		'--suites', '-s',
		choices=list(suites.keys()),
		default=list(suites.keys()),
		nargs='+',
		help='Which specific test suites to run'
	)

	args = parser.parse_args()

	if args.mode == 'suites':
		print 'Available suites: ' + ', '.join(suites.keys())
	elif args.mode == 'run':
		for sName in args.suites:
			print '#' * (19 + len(sName))
			print '# RUNNING SUITE: {} #'.format(sName)
			print '#' * (19 + len(sName))

			testResult = unittest.TextTestRunner(verbosity=2).run(suites[sName]())

